# Generated by Django 2.2 on 2021-04-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210423_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='duration',
            new_name='description',
        ),
        migrations.AddField(
            model_name='work_status',
            name='duration',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
